data_collection_duration: 60 # seconds
num_of_iterations: 6 # number of iterations for training
num_of_epochs: 5000 # number of epochs for training at each iteration
lr: 0.0005 # learning rate
weight_decay: 0.001 # weight decay